version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=rootpassword
    tmpfs:
      - /var/lib/mysql
    ports:
      - "3306:3306"
